-- MySQL Script generated by MySQL Workbench
-- Tue Sep 25 15:04:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema hijabi_fashion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hijabi_fashion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hijabi_fashion` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Client` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table4` (
)
ENGINE = InnoDB;

USE `hijabi_fashion` ;

-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Product` (
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`quality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`quality` (
  `idquality` INT NOT NULL,
  PRIMARY KEY (`idquality`),
  INDEX `quality` () VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`price` (
  `idprice` INT NOT NULL,
  PRIMARY KEY (`idprice`),
  CONSTRAINT `product`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Product` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quality`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`quality` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Barre Code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Barre Code` (
  `idBarre Code` INT NOT NULL,
  PRIMARY KEY (`idBarre Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Size` (
  `idSize` INT NOT NULL,
  PRIMARY KEY (`idSize`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Clothing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Clothing` (
  `idClothing` INT NOT NULL,
  PRIMARY KEY (`idClothing`),
  CONSTRAINT `barre code`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Barre Code` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `price`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`price` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quality`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`quality` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `size`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Size` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Shoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Shoes` (
  `idShoes` INT NOT NULL,
  PRIMARY KEY (`idShoes`),
  CONSTRAINT `price`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`price` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `size`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Size` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quality`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`quality` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `barre code`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Barre Code` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Accessories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Accessories` (
  `idAccessories` INT NOT NULL,
  PRIMARY KEY (`idAccessories`),
  CONSTRAINT `barre code`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Barre Code` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `price`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`price` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `size`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Size` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quality`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`quality` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Soldes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Soldes` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`table7`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`table7` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Fournisseurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Fournisseurs` (
  `idFournisseurs` INT NOT NULL,
  PRIMARY KEY (`idFournisseurs`),
  CONSTRAINT `product`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Product` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hijabi_fashion`.`Publicite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hijabi_fashion`.`Publicite` (
  `idPublicite` INT NOT NULL,
  PRIMARY KEY (`idPublicite`),
  CONSTRAINT `product`
    FOREIGN KEY ()
    REFERENCES `hijabi_fashion`.`Product` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
