-- MySQL Script generated by MySQL Workbench
-- Wed Sep 26 16:22:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tarif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarif` (
  `prix` INT NOT NULL,
  `heures` VARCHAR(45) NULL,
  `forfait` VARCHAR(45) NULL,
  `abonement` VARCHAR(45) NULL,
  PRIMARY KEY (`prix`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `idservices` INT NOT NULL,
  `restauration` VARCHAR(45) NULL,
  `courses` VARCHAR(45) NULL,
  `discussion` VARCHAR(45) NULL,
  `garderie` VARCHAR(45) NULL,
  `soutien scolaire` VARCHAR(45) NULL,
  `vigilance` VARCHAR(45) NULL,
  `pet attention` VARCHAR(45) NULL,
  `soin esthetique` VARCHAR(45) NULL,
  `langue` VARCHAR(45) NULL,
  `soutien administratif` VARCHAR(45) NULL,
  `bricolage` VARCHAR(45) NULL,
  `autres` VARCHAR(45) NULL,
  `entretiens du domicile` VARCHAR(45) NULL,
  `Tarif_prix` INT NOT NULL,
  PRIMARY KEY (`idservices`),
  INDEX `fk_services_Tarif1_idx` (`Tarif_prix` ASC) VISIBLE,
  CONSTRAINT `fk_services_Tarif1`
    FOREIGN KEY (`Tarif_prix`)
    REFERENCES `mydb`.`Tarif` (`prix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `idcategorie1` INT NOT NULL,
  `Femme` VARCHAR(45) NULL,
  `Homme` VARCHAR(45) NULL,
  `jeunes` VARCHAR(45) NULL,
  `seniors` VARCHAR(45) NULL,
  `Tarif_prix` INT NOT NULL,
  `service proposer` INT NOT NULL,
  PRIMARY KEY (`idcategorie1`),
  INDEX `fk_utilisateur_services_idx` (`service proposer` ASC) VISIBLE,
  INDEX `fk_utilisateur_Tarif1_idx` (`Tarif_prix` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_services`
    FOREIGN KEY (`service proposer`)
    REFERENCES `mydb`.`services` (`idservices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_Tarif1`
    FOREIGN KEY (`Tarif_prix`)
    REFERENCES `mydb`.`Tarif` (`prix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
